/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.cruds.Vacu;

/**
 *
 * @author 59399
 */
public class CrudVcuna extends javax.swing.JPanel {

    /**
     * Creates new form CrudVcuna
     */
    public CrudVcuna() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new rojeru_san.RSMTextFull();
        btnCancelar = new rojeru_san.RSButtonRiple();
        btnGuardar = new rojeru_san.RSButtonRiple();
        lblPropietario = new javax.swing.JLabel();
        lblMarca1 = new javax.swing.JLabel();
        txtCliente3 = new rojeru_san.RSMTextFull();
        lblMarca2 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        jPanel1.setBackground(new java.awt.Color(183, 224, 210));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(79, 107, 155));
        jLabel2.setText("Registro de Vacunas");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 320, 40));

        lblPlaca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblPlaca.setForeground(new java.awt.Color(79, 107, 155));
        lblPlaca.setText("id_Vacuna:");
        jPanel1.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 110, 40));

        txtPlaca.setForeground(new java.awt.Color(0, 53, 79));
        txtPlaca.setColorTransparente(true);
        txtPlaca.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtPlaca.setPlaceholder("Ejm: VACU_01");
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });
        jPanel1.add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 230, 40));

        btnCancelar.setBackground(new java.awt.Color(204, 51, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("Regresar a la lista de Vehiculos");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 153, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("Verificar y rellenar todos los campos");
        btnGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGuardarMouseClicked(evt);
            }
        });
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, -1, -1));

        lblPropietario.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblPropietario.setForeground(new java.awt.Color(79, 107, 155));
        lblPropietario.setText("Tipo:");
        jPanel1.add(lblPropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 50, 30));

        lblMarca1.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblMarca1.setForeground(new java.awt.Color(79, 107, 155));
        lblMarca1.setText("Fecha de expiración:");
        jPanel1.add(lblMarca1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 210, 40));

        txtCliente3.setForeground(new java.awt.Color(0, 53, 79));
        txtCliente3.setColorTransparente(true);
        txtCliente3.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtCliente3.setPlaceholder("");
        txtCliente3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCliente3KeyTyped(evt);
            }
        });
        jPanel1.add(txtCliente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 230, 40));

        lblMarca2.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblMarca2.setForeground(new java.awt.Color(79, 107, 155));
        lblMarca2.setText("Fecha de Creación:");
        jPanel1.add(lblMarca2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 190, 40));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 210, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 890, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
       
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
      
       
        
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGuardarMouseClicked

    }//GEN-LAST:event_btnGuardarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
       
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtCliente3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCliente3KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCliente3KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSButtonRiple btnCancelar;
    private rojeru_san.RSButtonRiple btnGuardar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMarca1;
    private javax.swing.JLabel lblMarca2;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPropietario;
    private rojeru_san.RSMTextFull txtCliente3;
    private rojeru_san.RSMTextFull txtPlaca;
    // End of variables declaration//GEN-END:variables
}
