package Vista.Factura;

import Conexion.Conexion_db;
import Models.Cliente;
import Models.EncabezadoFactura_1;
import Models.Producto;
import Models.Servicios;
import Vista.Menu.VistaMenu;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import com.db4o.query.Query;
import java.time.LocalDate;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Factura extends javax.swing.JPanel {

    /**
     * Creates new form Factura
     */
   
    public Factura() {
        
        initComponents();
        setearcabe();
        txtNombre1.setEnabled(false);
        txtdireccion.setEnabled(false);
        txtcedula.setEnabled(false);
        txttelefono.setEnabled(false);
        mostrarTablaProductos();
        mostrarDatosCliente();
        mostrarTablaServicios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablaproductos = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tblProductos = new javax.swing.JScrollPane();
        Tablproductos1 = new javax.swing.JTable();
        txtBuscar = new rojeru_san.RSMTextFull();
        jLabel3 = new javax.swing.JLabel();
        btnInsertar = new rsbuttongradiente.RSButtonGradiente();
        tablaClientes = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        txtBuscar1 = new rojeru_san.RSMTextFull();
        btnInsertarCliente = new rsbuttongradiente.RSButtonGradiente();
        TablaServicios = new javax.swing.JDialog();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();
        txtBuscar2 = new rojeru_san.RSMTextFull();
        jLabel6 = new javax.swing.JLabel();
        btnBuscar1 = new rsbuttongradiente.RSButtonGradiente();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblTituloFac = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblDatosCli = new javax.swing.JLabel();
        txttelefono = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtdireccion = new javax.swing.JTextField();
        lblverlis = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtableFactura = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        lblSubtotal = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblTotalFAc = new javax.swing.JLabel();
        btnNuevo = new javax.swing.JButton();
        btnGenerarVenta = new javax.swing.JButton();
        btnResibo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        lbllineas = new javax.swing.JLabel();
        lblcedula = new javax.swing.JLabel();
        txtcedula = new javax.swing.JTextField();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        txtcodigoFac = new javax.swing.JTextField();
        lblCuadro1 = new javax.swing.JLabel();
        lblcodFac1 = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        rSButton1 = new rojeru_san.RSButton();
        btnAñadirProductos = new javax.swing.JButton();
        txtfecha = new javax.swing.JTextField();
        lblCuadro = new javax.swing.JLabel();
        btnAñadirServicos = new javax.swing.JButton();
        txtDescuento = new javax.swing.JTextField();
        txtTotalfac = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        jLabel1.setText("Listado Productos");

        tblProductos.setBackground(new java.awt.Color(255, 255, 255));
        tblProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblProductos.setForeground(new java.awt.Color(255, 255, 255));

        Tablproductos1.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        Tablproductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProductos.setViewportView(Tablproductos1);

        txtBuscar.setFont(new java.awt.Font("Roboto Bold", 2, 14)); // NOI18N
        txtBuscar.setPlaceholder("ejm. Pro-01");

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel3.setText("Buscar");

        btnInsertar.setText("Insertar");
        btnInsertar.setColorPrimario(new java.awt.Color(0, 51, 153));
        btnInsertar.setColorPrimarioHover(new java.awt.Color(51, 0, 255));
        btnInsertar.setColorSecundario(new java.awt.Color(51, 153, 255));
        btnInsertar.setColorSecundarioHover(new java.awt.Color(153, 204, 255));
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 292, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tblProductos))
                        .addContainerGap())))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3)))
                .addGap(44, 44, 44)
                .addComponent(tblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tablaproductos.getContentPane().add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        jLabel4.setText("Listado Clientes");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setEnabled(false);

        tblClientes.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblClientes);

        txtBuscar1.setFont(new java.awt.Font("Roboto Bold", 2, 14)); // NOI18N
        txtBuscar1.setPlaceholder("ejm. 0106388747");

        btnInsertarCliente.setText("Insertar");
        btnInsertarCliente.setColorPrimario(new java.awt.Color(0, 51, 153));
        btnInsertarCliente.setColorPrimarioHover(new java.awt.Color(51, 0, 255));
        btnInsertarCliente.setColorSecundario(new java.awt.Color(51, 153, 255));
        btnInsertarCliente.setColorSecundarioHover(new java.awt.Color(153, 204, 255));
        btnInsertarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tablaClientesLayout = new javax.swing.GroupLayout(tablaClientes.getContentPane());
        tablaClientes.getContentPane().setLayout(tablaClientesLayout);
        tablaClientesLayout.setHorizontalGroup(
            tablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
            .addGroup(tablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tablaClientesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        tablaClientesLayout.setVerticalGroup(
            tablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
            .addGroup(tablaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(tablaClientesLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setFont(new java.awt.Font("Roboto Black", 0, 22)); // NOI18N
        jLabel5.setText("Listado Servicios");

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setToolTipText("");
        jScrollPane3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tblServicios.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cedula", "Nombre ", "Apellido", "Direccion", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblServicios);

        txtBuscar2.setFont(new java.awt.Font("Roboto Bold", 2, 14)); // NOI18N
        txtBuscar2.setPlaceholder("ejm. Ser-01");

        jLabel6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel6.setText("Buscar");

        btnBuscar1.setText("Buscar");
        btnBuscar1.setColorPrimario(new java.awt.Color(0, 51, 153));
        btnBuscar1.setColorPrimarioHover(new java.awt.Color(51, 0, 255));
        btnBuscar1.setColorSecundario(new java.awt.Color(51, 153, 255));
        btnBuscar1.setColorSecundarioHover(new java.awt.Color(153, 204, 255));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(39, 39, 39)
                        .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 372, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6)))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TablaServiciosLayout = new javax.swing.GroupLayout(TablaServicios.getContentPane());
        TablaServicios.getContentPane().setLayout(TablaServiciosLayout);
        TablaServiciosLayout.setHorizontalGroup(
            TablaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 863, Short.MAX_VALUE)
            .addGroup(TablaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TablaServiciosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        TablaServiciosLayout.setVerticalGroup(
            TablaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
            .addGroup(TablaServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(TablaServiciosLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 53, 79));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 53, 79));

        lblTituloFac.setBackground(new java.awt.Color(0, 53, 79));
        lblTituloFac.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblTituloFac.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloFac.setText("FACTURACION MECANICA YIN AND YANS");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Logomini1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTituloFac, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(282, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloFac, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 70));

        lblDireccion.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblDireccion.setText("Direccion:");
        jPanel3.add(lblDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        lblTelefono.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblTelefono.setText("Telefono:");
        jPanel3.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, -1, -1));

        lblDatosCli.setText("Datos del Cliente");
        jPanel3.add(lblDatosCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 10));
        jPanel3.add(txttelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 220, -1));

        lblFecha.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblFecha.setText("Fecha:");
        jPanel3.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, -1, -1));
        jPanel3.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 220, -1));

        lblverlis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblverlis, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 710, 70));

        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/boton-x (1).png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        jPanel3.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        btnAñadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mas (1).png"))); // NOI18N
        btnAñadir.setText("Buscar");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel3.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, 30));

        JtableFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo Producto/Servicio", "Nombre Producto/Servicio", "Precio Producto/Servicio", "Cantidad Producto/Servicio", "Subtotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JtableFactura);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 710, 90));

        jPanel5.setBackground(new java.awt.Color(0, 53, 79));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 888, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 890, 20));

        lblSubtotal.setText("SubTotal:");
        jPanel3.add(lblSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, 20));

        lblDescuento.setText("%Descuento:");
        jPanel3.add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        lblIva.setText("IVA 15%:");
        jPanel3.add(lblIva, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        lblTotalFAc.setText("Total Factura:");
        jPanel3.add(lblTotalFAc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/registro (1)_1.png"))); // NOI18N
        jPanel3.add(btnNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 80, 70));

        btnGenerarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/dinero.png"))); // NOI18N
        jPanel3.add(btnGenerarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 80, 70));

        btnResibo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/impresion.png"))); // NOI18N
        jPanel3.add(btnResibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 300, 80, 70));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/rechazar.png"))); // NOI18N
        jPanel3.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 390, 80, 70));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar-sesion.png"))); // NOI18N
        jPanel3.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 80, 70));

        lbllineas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lbllineas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 710, 110));

        lblcedula.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblcedula.setText("Cedula:");
        jPanel3.add(lblcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        jPanel3.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 190, 30));

        lblNombre1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblNombre1.setText("Cliente:");
        jPanel3.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        jPanel3.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 190, -1));
        jPanel3.add(txtcodigoFac, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 130, -1));

        lblCuadro1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblCuadro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 710, 110));

        lblcodFac1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        lblcodFac1.setText("N° Factura:");
        jPanel3.add(lblcodFac1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 70, -1));
        jPanel3.add(txtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 100, -1));

        rSButton1.setBackground(new java.awt.Color(0, 204, 0));
        rSButton1.setText("Finalizar Factura");
        jPanel3.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, -1, -1));

        btnAñadirProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mas (1).png"))); // NOI18N
        btnAñadirProductos.setText("Añadir Productos");
        btnAñadirProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirProductosActionPerformed(evt);
            }
        });
        jPanel3.add(btnAñadirProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, -1, -1));
        jPanel3.add(txtfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 90, 220, -1));

        lblCuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.add(lblCuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 710, 40));

        btnAñadirServicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mas (1).png"))); // NOI18N
        btnAñadirServicos.setText("Añadir Servicios ");
        btnAñadirServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirServicosActionPerformed(evt);
            }
        });
        jPanel3.add(btnAñadirServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));
        jPanel3.add(txtDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 100, -1));
        jPanel3.add(txtTotalfac, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 100, 20));
        jPanel3.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 490, 100, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 640));

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        seteardatosPro();
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnAñadirProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirProductosActionPerformed
        activarJdialog(tablaproductos);
    }//GEN-LAST:event_btnAñadirProductosActionPerformed

    private void btnInsertarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarClienteActionPerformed
             CargarCliente();
    }//GEN-LAST:event_btnInsertarClienteActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
            activarJadialog( tablaClientes);
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnAñadirServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirServicosActionPerformed
           activarJadialogser(TablaServicios);
    }//GEN-LAST:event_btnAñadirServicosActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
         seteardatosServicio();
    }//GEN-LAST:event_btnBuscar1ActionPerformed
    private static String obtenerProximoCodigoFactura(ObjectContainer db) {
        // Consultar todos los servicios
        ObjectSet<EncabezadoFactura_1> result = db.queryByExample(EncabezadoFactura_1.class);

        // Determinar el máximo ID numérico existente
        int maxID = 0;
        while (result.hasNext()) {
            EncabezadoFactura_1 facturacion = result.next();
            String codigo = facturacion.getCodigo_encabezadoFactura();
            if (codigo != null && codigo.startsWith("FAC-000")) {
                int id = Integer.parseInt(codigo.substring(3)); // Extraer la parte numérica del código
                if (id > maxID) {
                    maxID = id;
                }
            }
        }

        // El próximo ID es el máximo + 1
        int siguienteID = maxID + 1;
        // Retornar el nuevo código concatenado con "SER"
        return "FAC-000" + siguienteID;

    }

    public void setearcabe() {
        ObjectContainer baseBD = Conexion_db.ConectarBD();
        String fac = obtenerProximoCodigoFactura(baseBD);
        txtcodigoFac.setText(fac);
        txtcodigoFac.setEnabled(false);
        txtfecha.setText(obtenerFechaActual());
        txtfecha.setEnabled(false);
        baseBD.close();
    }

    public static String obtenerFechaActual() {
        LocalDate fechaActual = LocalDate.now();
        String fechita = fechaActual.toString();
        return fechita;
    }

    private void activarJdialog(JDialog tablaProductos) {

        tablaProductos.setTitle("Listado Productos");
        tablaProductos.setSize(680, 330);
        tablaProductos.setLocationRelativeTo(this);
        tablaProductos.setVisible(true);
    }

    private void mostrarTablaProductos() {
        ObjectContainer BaseBD = Conexion_db.ConectarBD();
        Producto producto = new Producto(null, null, null, null, 0, 0, 0, null, null);
        ObjectSet<Producto> resul = BaseBD.get(producto);

        String matriz[][] = new String[resul.size()][4];

        for (int i = 0; i < resul.size(); i++) {
            Producto prod = (Producto) resul.next();

            matriz[i][0] = prod.getCodigo_Producto();
            matriz[i][1] = prod.getNombre_Producto();
            matriz[i][2] = String.valueOf(prod.getPrecio_Producto());
            matriz[i][3] = String.valueOf(prod.getNumeroProductos_Producto());
        }

        Tablproductos1.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "Código Producto", "Nombre Producto", "Precio", "Número de Productos"
                }
        ));
        BaseBD.close();
    }

    public void seteardatosPro() {
        int selectedRow = Tablproductos1.getSelectedRow();
        if (selectedRow != -1) {
            String codigoProducto = (String) Tablproductos1.getValueAt(selectedRow, 0);
            String nombreProducto = (String) Tablproductos1.getValueAt(selectedRow, 1);
            String precioProducto = (String) Tablproductos1.getValueAt(selectedRow, 2);
            //validar
            String numeroProductos = JOptionPane.showInputDialog("Ingrese la cantidad de Productos");
            DefaultTableModel modelFactura = (DefaultTableModel) JtableFactura.getModel();
            modelFactura.addRow(new Object[]{codigoProducto, nombreProducto, precioProducto, numeroProductos});
            tablaproductos.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null, "No se seleccionó ningún producto");
        }
    }
    //clientes

    private void activarJadialog(JDialog tablaClientes) {

        tablaClientes.setTitle("Listado Clientes");
        tablaClientes.setSize(680, 330);
        tablaClientes.setLocationRelativeTo(this);
        tablaClientes.setVisible(true);
    }

    private void mostrarDatosCliente() {

        ObjectContainer BaseBD = Conexion_db.ConectarBD();
        tblClientes.setEnabled(true);

        ObjectSet<Cliente> resultado = BaseBD.get(Cliente.class);

        String matriz[][] = new String[resultado.size()][5];
        int i = 0;
        for (Cliente cli : resultado) {

                             
            matriz[i][0] = cli.getCedula();
            matriz[i][1] = cli.getNombres();
            matriz[i][2] = cli.getApellidos();
            matriz[i][3] = cli.getDireccion();            
            matriz[i][4] = cli.getCelular();
            
            i++;
        }

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{ "Cedula", "Nombres", "Apellidos", "Direccion",  "Celular",} ));
        BaseBD.close();
    }

    
    public final void CargarCliente() {
    Boolean encontrado = false;
    // ESTABLECER CONEXION CON LA BASE DE DATOS
    ObjectContainer BaseBD = Conexion_db.ConectarBD();

    // consulta
    Query clienteQuery = BaseBD.query(); // metodo para iniciar una consulta
     clienteQuery.constrain(Cliente.class); // buscaremos en la clase Cliente   
    ObjectSet<Cliente> resultado = clienteQuery.execute(); // Ejecutamos la consulta y almacenamos en "resultado"

    // Iterar sobre los resultados para obtener los atributos
    for (Cliente miCliente : resultado) {
        // Con esto seteamos en los campos recibiendo del objeto
        txtcedula.setText(miCliente.getCedula());       
        txtNombre1.setText(miCliente.getNombres());
        txtdireccion.setText(miCliente.getDireccion());
        txttelefono.setText(miCliente.getCelular());
        encontrado = true;
    }
    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "No se encontró Cliente");
    }

    BaseBD.close();
}
    //Servicios 
    private void mostrarTablaServicios() {
    ObjectContainer BaseBD = Conexion_db.ConectarBD();
    Servicios servicio = new Servicios();
    ObjectSet<Servicios> resul = BaseBD.get(servicio);

    String[][] matriz = new String[resul.size()][8];

    int i = 0;
    while (resul.hasNext()) {
        Servicios serv = resul.next();

        matriz[i][0] = serv.getCodigo_Servicio();
        matriz[i][1] = serv.getNombre_Servicio();        
        matriz[i][2] = String.valueOf(serv.getPrecioTotal_Servicio());
        
       

        i++;
    }

    tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String[]{
                "Código Servicio", "Nombre Servicio", "Precio Total"} ));
    BaseBD.close();
}
  private void activarJadialogser(JDialog TablaServicios) {

        TablaServicios.setTitle("Listado Servicios");
        TablaServicios.setSize(680, 330);
        TablaServicios.setLocationRelativeTo(this);
        TablaServicios.setVisible(true);
    } 
  public void seteardatosServicio() {
    int selectedRow = tblServicios.getSelectedRow();
    if (selectedRow != -1) {
        String codigoServicio = (String) tblServicios.getValueAt(selectedRow, 0);
        String nombreServicio = (String) tblServicios.getValueAt(selectedRow, 1);
        String precioServicio = (String) tblServicios.getValueAt(selectedRow, 2);
        // validar
        String numero = JOptionPane.showInputDialog("Ingrese el numero de vehiculos alos que se les realizo el servicio");
        DefaultTableModel modelFactura = (DefaultTableModel) JtableFactura.getModel();
        modelFactura.addRow(new Object[]{codigoServicio, nombreServicio, precioServicio,numero});
        tblServicios.setVisible(false);
    } else {
        JOptionPane.showMessageDialog(null, "No se seleccionó ningún servicio");
    }
}
  //subtotal por producto/Servicio 
  
  //subtotal total 
  //iva al 15%
  //total de la factura
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JtableFactura;
    private javax.swing.JDialog TablaServicios;
    private javax.swing.JTable Tablproductos1;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnAñadirProductos;
    private javax.swing.JButton btnAñadirServicos;
    private rsbuttongradiente.RSButtonGradiente btnBuscar1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerarVenta;
    private rsbuttongradiente.RSButtonGradiente btnInsertar;
    private rsbuttongradiente.RSButtonGradiente btnInsertarCliente;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnResibo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblCuadro;
    private javax.swing.JLabel lblCuadro1;
    private javax.swing.JLabel lblDatosCli;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTituloFac;
    private javax.swing.JLabel lblTotalFAc;
    private javax.swing.JLabel lblcedula;
    private javax.swing.JLabel lblcodFac1;
    private javax.swing.JLabel lbllineas;
    private javax.swing.JLabel lblverlis;
    private rojeru_san.RSButton rSButton1;
    private javax.swing.JDialog tablaClientes;
    private javax.swing.JDialog tablaproductos;
    private javax.swing.JTable tblClientes;
    private javax.swing.JScrollPane tblProductos;
    private javax.swing.JTable tblServicios;
    private rojeru_san.RSMTextFull txtBuscar;
    private rojeru_san.RSMTextFull txtBuscar1;
    private rojeru_san.RSMTextFull txtBuscar2;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTotalfac;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigoFac;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtfecha;
    private javax.swing.JTextField txttelefono;
    // End of variables declaration//GEN-END:variables
}
