libs.absolutelayout.classpath=\
    ${base}/absolutelayout/AbsoluteLayout.jar;\
    ${base}/absolutelayout/db4o-7.2.44.10827-java5.jar;\
    ${base}/absolutelayout/db4o-7.2.44.10827-java5-2.jar;\
    ${base}/absolutelayout/RojeruSan.lib.jar;\
    ${base}/AbsoluteLayout.jar
libs.absolutelayout.displayName=Absolute Layout
libs.CopyLibs.classpath=\
    ${base}/CopyLibs/org-netbeans-modules-java-j2seproject-copylibstask.jar
libs.CopyLibs.displayName=CopyLibs Task
libs.CopyLibs.prop-version=3.0
libs.YingsYangs.classpath=\
    ${base}/jcalendar-1.4.jar;\
    ${base}/db4o-7.2.44.10827-java5.jar;\
    ${base}/AbsoluteLayout.jar;\
    ${base}/RojeruSan.lib.jar;\
    ${base}/RSButtonGradiente.jar;\
    ${base}/RSCalendar v2.0.jar;\
    ${base}/RSAnimation.jar;\
    ${base}/jcommon-1.0.23.jar;\
    ${base}/jfreechart-1.0.19.zip;\
    ${base}/jfreechart-1.0.19.jar;\
    ${base}/barcodes-7.1.16.jar;\
    ${base}/font-asian-7.1.16.jar;\
    ${base}/forms-7.1.16.jar;\
    ${base}/hyph-7.1.16.jar;\
    ${base}/io-7.1.16.jar;\
    ${base}/kernel-7.1.16.jar;\
    ${base}/layout-7.1.16.jar;\
    ${base}/log4j-1.2.17.jar;\
    ${base}/pdfa-7.1.16.jar;\
    ${base}/pdftest-7.1.16.jar;\
    ${base}/sign-7.1.16.jar;\
    ${base}/slf4j-api-1.7.9.jar;\
    ${base}/slf4j-log4j12-1.7.9.jar;\
    ${base}/styled-xml-parser-7.1.16.jar;\
    ${base}/svg-7.1.16.jar;\
    ${base}/activation-1.1.1.jar;\
    ${base}/javax.mail-1.6.1.jar;\
    ${base}/YingsYangs/AbsoluteLayout.jar;\
    ${base}/YingsYangs/RSAnimation.jar;\
    ${base}/YingsYangs/RSButtonGradiente.jar;\
    ${base}/YingsYangs/RSCalendar v2.0.jar;\
    ${base}/YingsYangs/RojeruSan.lib.jar;\
    ${base}/YingsYangs/activation-1.1.1.jar;\
    ${base}/YingsYangs/barcodes-7.1.16.jar;\
    ${base}/YingsYangs/db4o-7.2.44.10827-java5-2.jar;\
    ${base}/YingsYangs/db4o-7.2.44.10827-java5.jar;\
    ${base}/YingsYangs/font-asian-7.1.16.jar;\
    ${base}/YingsYangs/forms-7.1.16.jar;\
    ${base}/YingsYangs/hyph-7.1.16.jar;\
    ${base}/YingsYangs/io-7.1.16.jar;\
    ${base}/YingsYangs/javax.mail-1.6.1.jar;\
    ${base}/YingsYangs/javax.mail-api-1.6.2.jar;\
    ${base}/YingsYangs/jcalendar-1.4.jar;\
    ${base}/YingsYangs/jcommon-1.0.23.jar;\
    ${base}/YingsYangs/jfreechart-1.0.19-demo.jar;\
    ${base}/YingsYangs/jfreechart-1.0.19.jar;\
    ${base}/YingsYangs/jfreechart-1.0.19.zip;\
    ${base}/YingsYangs/kernel-7.1.16.jar;\
    ${base}/YingsYangs/layout-7.1.16.jar;\
    ${base}/YingsYangs/log4j-1.2.17.jar;\
    ${base}/YingsYangs/pdfa-7.1.16.jar;\
    ${base}/YingsYangs/pdftest-7.1.16.jar;\
    ${base}/YingsYangs/sign-7.1.16.jar;\
    ${base}/YingsYangs/slf4j-api-1.7.9.jar;\
    ${base}/YingsYangs/slf4j-log4j12-1.7.9.jar;\
    ${base}/YingsYangs/styled-xml-parser-7.1.16.jar;\
    ${base}/YingsYangs/svg-7.1.16.jar
libs.YingsYangs.displayName=YingsYangs
