
package Vista.PanelSubmenus;

import Citas.CrudlistadosServicios;
import Vista.Catálogo.CrudPanelServicios;
import Vista.Menu.VistaMenu;
import Vista.Tables.TablaCategoriaSer;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JToggleButton;

public class PanelSubmenuServicios extends javax.swing.JPanel {

    /**
     * Creates new form PanelSubmenuServicios
     */
    public PanelSubmenuServicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCitasAgendadas = new javax.swing.JToggleButton();
        btnordenesTrabajo = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();
        btngestionser1 = new javax.swing.JToggleButton();
        btnCategoria1 = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnCitasAgendadas.setFont(new java.awt.Font("Roboto Medium", 1, 11)); // NOI18N
        btnCitasAgendadas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gestion-de-servicios.png"))); // NOI18N
        btnCitasAgendadas.setText("CITAS AGENDADAS");

        btnordenesTrabajo.setFont(new java.awt.Font("Roboto Medium", 1, 11)); // NOI18N
        btnordenesTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/portapapeles.png"))); // NOI18N
        btnordenesTrabajo.setText("ORDENES DE TRABAJO");
        btnordenesTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnordenesTrabajoActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 53, 79));

        btngestionser1.setFont(new java.awt.Font("Roboto Medium", 1, 11)); // NOI18N
        btngestionser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/gestionarServicios35.png"))); // NOI18N
        btngestionser1.setText("GESTION DE SERVICIOS");
        btngestionser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngestionser1ActionPerformed(evt);
            }
        });

        btnCategoria1.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        btnCategoria1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/aplicacion.png"))); // NOI18N
        btnCategoria1.setText("CATEGORIA  SERVICIOS");
        btnCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoria1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btnordenesTrabajo)
                .addGap(10, 10, 10)
                .addComponent(btnCitasAgendadas)
                .addGap(18, 18, 18)
                .addComponent(btngestionser1)
                .addGap(18, 18, 18)
                .addComponent(btnCategoria1)
                .addContainerGap(17, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnordenesTrabajo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCitasAgendadas, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btngestionser1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnCategoria1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnordenesTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnordenesTrabajoActionPerformed
        CrudlistadosServicios serv = new CrudlistadosServicios();
       ShowpanelCruds(serv);
    }//GEN-LAST:event_btnordenesTrabajoActionPerformed

    private void btngestionser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngestionser1ActionPerformed
       CrudPanelServicios servcito = new CrudPanelServicios();
       ShowpanelCruds(servcito);
    }//GEN-LAST:event_btngestionser1ActionPerformed

    private void btnCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoria1ActionPerformed
        TablaCategoriaSer tblcat = new TablaCategoriaSer();
        ShowpanelCruds(tblcat);
    }//GEN-LAST:event_btnCategoria1ActionPerformed
 private void ShowpanelCruds(JPanel p) {
        p.setSize(870, 630);
        p.setLocation(0, 0);
        VistaMenu.PanelPrincipal.removeAll();
        VistaMenu.PanelPrincipal.add(p, BorderLayout.CENTER);
        VistaMenu.PanelPrincipal.revalidate();
        VistaMenu.PanelPrincipal.repaint();
    }

    public JToggleButton getBtnCategoria1() {
        return btnCategoria1;
    }

    public void setBtnCategoria1(JToggleButton btnCategoria1) {
        this.btnCategoria1 = btnCategoria1;
    }

    public JToggleButton getBtnCitasAgendadas() {
        return btnCitasAgendadas;
    }

    public void setBtnCitasAgendadas(JToggleButton btnCitasAgendadas) {
        this.btnCitasAgendadas = btnCitasAgendadas;
    }

    public JToggleButton getBtngestionser1() {
        return btngestionser1;
    }

    public void setBtngestionser1(JToggleButton btngestionser1) {
        this.btngestionser1 = btngestionser1;
    }

    public JToggleButton getBtnordenesTrabajo() {
        return btnordenesTrabajo;
    }

    public void setBtnordenesTrabajo(JToggleButton btnordenesTrabajo) {
        this.btnordenesTrabajo = btnordenesTrabajo;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCategoria1;
    private javax.swing.JToggleButton btnCitasAgendadas;
    private javax.swing.JToggleButton btngestionser1;
    private javax.swing.JToggleButton btnordenesTrabajo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
