/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista.Cruds;

import Conexion.Conexion_db;
import Models.Cita;
import com.db4o.*;
import com.db4o.query.Query;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aberr
 */
public class PanelCitasPendientesMecanico extends javax.swing.JPanel {

    /**
     * Creates new form PanelCitasPendientesMecanico
     */
    public PanelCitasPendientesMecanico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCedulaMecanico = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(890, 650));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("PENDIENTES:");

        txtCedulaMecanico.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 576, Short.MAX_VALUE)
                .addComponent(txtCedulaMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtCedulaMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(587, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    public void mostrarCitasActivasPorMecanico() {
    ObjectContainer BaseBD = Conexion_db.ConectarBD();
    try {
        String cedulaMecanico = txtCedulaMecanico.getText();
        Query query = BaseBD.query();
        query.constrain(Cita.class);
        query.descend("Id_mecanico").constrain(cedulaMecanico);
        query.descend("estado").constrain(Cita.Estado.ACTIVO);
        ObjectSet<Cita> citas = query.execute();

        // Crear un modelo de tabla para mostrar las citas
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Cita");
        modelo.addColumn("Fecha");
        modelo.addColumn("Hora");
        modelo.addColumn("Estado");

        for (Cita cita : citas) {
            Object[] fila = new Object[] {
                cita.getCodigo_cita(),
                cita.getFecha_cita(),
                cita.getHora(),
                new Boolean(false) // Checkbox vacío para indicar estado activo
            };
            modelo.addRow(fila);
        }

        // Crear una tabla para mostrar las citas
        JTable tabla = new JTable(modelo);
        tabla.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(new JCheckBox()));

        // Agregar la tabla a un scrollpane y mostrarla en un dialogo
        JScrollPane scrollPane = new JScrollPane(tabla);
        JOptionPane.showMessageDialog(null, scrollPane, "Citas activas del mecanico", JOptionPane.INFORMATION_MESSAGE);

        // Agregar un listener para detectar cambios en los checkboxes
        tabla.getModel().addTableModelListener(new TableModelListener() {
            public void tableChanged(TableModelEvent e) {
                int fila = e.getFirstRow();
                int columna = e.getColumn();
                if (columna == 3) { // Columna de estado
                    Boolean estado = (Boolean) tabla.getValueAt(fila, columna);
                    Cita cita = citas.get(fila);
                    if (estado) {
                        cita.setEstado(Cita.Estado.INACTIVO);
                    } else {
                        cita.setEstado(Cita.Estado.ACTIVO);
                    }
                    BaseBD.store(cita);
                }
            }
        });
    } finally {
        BaseBD.close();
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCedulaMecanico;
    // End of variables declaration//GEN-END:variables
}
