
package Vista.Cruds.CRUDS1;

import Conexion.Conexion_db;
import Models.Mecanico;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

public class CrudPanelMecanico extends javax.swing.JPanel {

    /**
     * Creates new form CrudPanelMecanico1
     */
    
    public void GuardarMecanico( String titulo, double Sueldo, String cedula, String nombres, String apellidos, String direccion, String correo, String celular, String genero,
            String fechaNacimiento, String estadoCivil, String nombreUsuario, String password, String correoRecuperacion ) {

        ObjectContainer BaseBD = Conexion_db.ConectarBD();
        
        int siguienteID = obtenerProximoIDMecanico(BaseBD);
        
        Mecanico mecanico1 = new Mecanico( titulo,  Sueldo,  cedula,  nombres,  apellidos,  direccion,  correo,  celular,  genero,
             fechaNacimiento,  estadoCivil,  nombreUsuario,  password,  correoRecuperacion );
      
        mecanico1.setiD_Mecanico(siguienteID);
        BaseBD.close();

        if (VerificarMecanico(cedula) == 0) {

            BaseBD = Conexion_db.ConectarBD();
            BaseBD.set(mecanico1);
           BaseBD.close();

            JOptionPane.showMessageDialog(this, "Mecanico Guardado");

        } else {

            JOptionPane.showMessageDialog(this, "Ya existe el Mecanico ");
        }
    }

    public static int VerificarMecanico(String cedula) {

        ObjectContainer BaseBD = Conexion_db.ConectarBD();

        Mecanico buscaVendedor = new Mecanico(null,0.0,cedula, null, null, null, null,
                null,  null, null, null, null, null, null);

        ObjectSet resultado = BaseBD.get(buscaVendedor);
        
        int coincidencias = resultado.size();

        BaseBD.close();
        return coincidencias;
    }

    // Método para obtener el próximo ID_Vendedor disponible
private int obtenerProximoIDMecanico(ObjectContainer db) {
    // Consultar el máximo ID_Vendedor almacenado en la base de datos
    ObjectSet<Mecanico> result = db.queryByExample(Mecanico.class);
    int maxID = 0;
    while (result.hasNext()) {
        Mecanico mecanico = result.next();
        if (mecanico.getiD_Mecanico()> maxID) {
            maxID = mecanico.getiD_Mecanico();
        }
    }
    // El próximo ID es el máximo + 1
    return maxID + 1;
}
    
    
    public CrudPanelMecanico() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Cedula_Meca = new javax.swing.JLabel();
        lblNombres_Meca = new javax.swing.JLabel();
        lblApellidos_Meca = new javax.swing.JLabel();
        lblDireccion_Meca = new javax.swing.JLabel();
        lblCorreo_Meca = new javax.swing.JLabel();
        lblTituloMec = new javax.swing.JLabel();
        lblFEchaNac_Meca = new javax.swing.JLabel();
        lblGenero_Meca = new javax.swing.JLabel();
        lblEstadoCivil_Meca = new javax.swing.JLabel();
        txtCedulaMec = new rojeru_san.RSMTextFull();
        txtNombresMec = new rojeru_san.RSMTextFull();
        txtApellidosMec = new rojeru_san.RSMTextFull();
        txtDireccionMec = new rojeru_san.RSMTextFull();
        txtCorreoMec = new rojeru_san.RSMTextFull();
        txtTituloMec = new rojeru_san.RSMTextFull();
        btnCancelar = new rojeru_san.RSButtonRiple();
        jDateFechaNacMec = new com.toedter.calendar.JDateChooser();
        cbxGeneroMec = new javax.swing.JComboBox<>();
        cbxEstadoCivilMec = new javax.swing.JComboBox<>();
        btnGuardar = new rojeru_san.RSButtonRiple();
        lblPassword_Meca = new javax.swing.JLabel();
        txtPasswordMec = new rojeru_san.RSMTextFull();
        lblSueldoMec = new javax.swing.JLabel();
        lblCelular_Meca = new javax.swing.JLabel();
        txtSueldoMec = new rojeru_san.RSMTextFull();
        txtCelularMec = new rojeru_san.RSMTextFull();

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 53, 79));
        jLabel2.setText("Registro Mecanico");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 260, 40));

        Cedula_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        Cedula_Meca.setForeground(new java.awt.Color(0, 53, 79));
        Cedula_Meca.setText("Cédula/Usuario:");
        jPanel2.add(Cedula_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, 40));

        lblNombres_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblNombres_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblNombres_Meca.setText("Nombres:");
        jPanel2.add(lblNombres_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 100, 40));

        lblApellidos_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblApellidos_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblApellidos_Meca.setText("Apellidos:");
        jPanel2.add(lblApellidos_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, 40));

        lblDireccion_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblDireccion_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblDireccion_Meca.setText("Dirección");
        jPanel2.add(lblDireccion_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 90, 40));

        lblCorreo_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblCorreo_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblCorreo_Meca.setText("Correo Electrónico:");
        jPanel2.add(lblCorreo_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 190, 40));

        lblTituloMec.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblTituloMec.setForeground(new java.awt.Color(0, 53, 79));
        lblTituloMec.setText("Titulo:");
        jPanel2.add(lblTituloMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 60, 40));

        lblFEchaNac_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblFEchaNac_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblFEchaNac_Meca.setText("Fecha Nacimiento:");
        jPanel2.add(lblFEchaNac_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 180, 40));

        lblGenero_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblGenero_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblGenero_Meca.setText("Género:");
        jPanel2.add(lblGenero_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 80, 40));

        lblEstadoCivil_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblEstadoCivil_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblEstadoCivil_Meca.setText("Estado Civil:");
        jPanel2.add(lblEstadoCivil_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 120, 40));

        txtCedulaMec.setForeground(new java.awt.Color(0, 53, 79));
        txtCedulaMec.setColorTransparente(true);
        txtCedulaMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtCedulaMec.setPlaceholder("0123456789");
        jPanel2.add(txtCedulaMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 200, 40));

        txtNombresMec.setForeground(new java.awt.Color(0, 53, 79));
        txtNombresMec.setColorTransparente(true);
        txtNombresMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtNombresMec.setPlaceholder("Escriba los nombres");
        jPanel2.add(txtNombresMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 200, 40));

        txtApellidosMec.setForeground(new java.awt.Color(0, 53, 79));
        txtApellidosMec.setColorTransparente(true);
        txtApellidosMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtApellidosMec.setPlaceholder("Escriba los apellidos");
        jPanel2.add(txtApellidosMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 200, 40));

        txtDireccionMec.setForeground(new java.awt.Color(0, 53, 79));
        txtDireccionMec.setColorTransparente(true);
        txtDireccionMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtDireccionMec.setPlaceholder("Escriba la dirección");
        jPanel2.add(txtDireccionMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 200, 40));

        txtCorreoMec.setForeground(new java.awt.Color(0, 53, 79));
        txtCorreoMec.setColorTransparente(true);
        txtCorreoMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtCorreoMec.setPlaceholder("Escriba su correo electronico");
        jPanel2.add(txtCorreoMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 250, 40));

        txtTituloMec.setForeground(new java.awt.Color(0, 53, 79));
        txtTituloMec.setColorTransparente(true);
        txtTituloMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtTituloMec.setPlaceholder("Escriba su titulo");
        jPanel2.add(txtTituloMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, 230, 40));

        btnCancelar.setBackground(new java.awt.Color(255, 51, 51));
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 520, -1, -1));
        jPanel2.add(jDateFechaNacMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 170, 140, 30));

        cbxGeneroMec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino\t\t", "Femenino" }));
        jPanel2.add(cbxGeneroMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 230, 150, 30));

        cbxEstadoCivilMec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Casado", "Viudo", "Union Libre" }));
        jPanel2.add(cbxEstadoCivilMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 150, 30));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, -1, -1));

        lblPassword_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblPassword_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblPassword_Meca.setText("Contraseña:");
        jPanel2.add(lblPassword_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 40));

        txtPasswordMec.setForeground(new java.awt.Color(0, 53, 79));
        txtPasswordMec.setColorTransparente(true);
        txtPasswordMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtPasswordMec.setPlaceholder("123abc");
        jPanel2.add(txtPasswordMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 200, 40));

        lblSueldoMec.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblSueldoMec.setForeground(new java.awt.Color(0, 53, 79));
        lblSueldoMec.setText("Sueldo:");
        jPanel2.add(lblSueldoMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 80, 40));

        lblCelular_Meca.setFont(new java.awt.Font("Roboto Medium", 0, 21)); // NOI18N
        lblCelular_Meca.setForeground(new java.awt.Color(0, 53, 79));
        lblCelular_Meca.setText("Celular:");
        jPanel2.add(lblCelular_Meca, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 80, 40));

        txtSueldoMec.setForeground(new java.awt.Color(0, 53, 79));
        txtSueldoMec.setColorTransparente(true);
        txtSueldoMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtSueldoMec.setPlaceholder("Escriba el sueldo");
        jPanel2.add(txtSueldoMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 380, 230, 40));

        txtCelularMec.setForeground(new java.awt.Color(0, 53, 79));
        txtCelularMec.setColorTransparente(true);
        txtCelularMec.setFont(new java.awt.Font("Roboto Light", 1, 14)); // NOI18N
        txtCelularMec.setPlaceholder("Escriba su número celular");
        jPanel2.add(txtCelularMec, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 100, 230, 40));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 448, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 448, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(0, 319, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 319, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 896, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked

    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
 boolean usuarioRepetido = false;
        
        if (VerificarMecanico(txtCedulaMec.getText()) != 0) {
            JOptionPane.showMessageDialog(null, "Mecanico ya registrado");
            usuarioRepetido = true;
        }

        if (!usuarioRepetido) {
            
            Boolean valido = false;
            
            Date fechaNacimientoDate = jDateFechaNacMec.getDate(); // Obtener la fecha de nacimiento del JDateChooser

            // Formatear la fecha como String en el formato deseado (por ejemplo, "dd/MM/yyyy")
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            String fechaNacimiento = sdf.format(fechaNacimientoDate);

           
            if (valido = txtCedulaMec.getText().matches("\\d{10}")) {
                if (valido = txtNombresMec.getText().toUpperCase().matches("^[a-zA-Z]+$")) {
                    if (valido = txtApellidosMec.getText().toUpperCase().matches("^[a-zA-Z]+$")) {
                        if (valido = txtDireccionMec.getText().toUpperCase().matches("^[a-zA-Z]+$")) {
                            if (valido = txtCorreoMec.getText().matches("^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,6}$")) {
                                if (valido = txtCelularMec.getText().matches("^09\\d{8}$")) {

                                    
                                    GuardarMecanico(fechaNacimiento, ERROR, fechaNacimiento, fechaNacimiento, fechaNacimiento,
                                            fechaNacimiento, fechaNacimiento, fechaNacimiento, fechaNacimiento, fechaNacimiento,
                                            fechaNacimiento, fechaNacimiento, fechaNacimiento, fechaNacimiento);
                                    

                                } else {
                                    JOptionPane.showMessageDialog(null, "Ingrese un celular valido");
                                }

                            } else {
                                JOptionPane.showMessageDialog(null, "Ingrese un correo valida");
                            }

                        } else {
                            JOptionPane.showMessageDialog(null, "Ingrese una direccion valida");
                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Ingrese un apellido valido");
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Ingrese un nombre valido");
                }

            } else {
                JOptionPane.showMessageDialog(null, "Ingrese una cedula valida");
            }

            
        }

    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cedula_Meca;
    private rojeru_san.RSButtonRiple btnCancelar;
    private rojeru_san.RSButtonRiple btnGuardar;
    private javax.swing.JComboBox<String> cbxEstadoCivilMec;
    private javax.swing.JComboBox<String> cbxGeneroMec;
    private com.toedter.calendar.JDateChooser jDateFechaNacMec;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lblApellidos_Meca;
    private javax.swing.JLabel lblCelular_Meca;
    private javax.swing.JLabel lblCorreo_Meca;
    private javax.swing.JLabel lblDireccion_Meca;
    private javax.swing.JLabel lblEstadoCivil_Meca;
    private javax.swing.JLabel lblFEchaNac_Meca;
    private javax.swing.JLabel lblGenero_Meca;
    private javax.swing.JLabel lblNombres_Meca;
    private javax.swing.JLabel lblPassword_Meca;
    private javax.swing.JLabel lblSueldoMec;
    private javax.swing.JLabel lblTituloMec;
    private rojeru_san.RSMTextFull txtApellidosMec;
    private rojeru_san.RSMTextFull txtCedulaMec;
    private rojeru_san.RSMTextFull txtCelularMec;
    private rojeru_san.RSMTextFull txtCorreoMec;
    private rojeru_san.RSMTextFull txtDireccionMec;
    private rojeru_san.RSMTextFull txtNombresMec;
    private rojeru_san.RSMTextFull txtPasswordMec;
    private rojeru_san.RSMTextFull txtSueldoMec;
    private rojeru_san.RSMTextFull txtTituloMec;
    // End of variables declaration//GEN-END:variables
}
