
package Vista.Menu;


import Citas.Citas;

import Vista.Catálogo.CatalogoProductos;


import Vista.Factura.Factura;
import Vista.Home.Home;
import Vista.PanelSubmenus.*;
import Vista.PanelTitulos.*;

import Vista.Tables.TablaProductos;
import Vista.Tables.TablaProveedor;
import Vista.Tables.TablaServicios;

import Vista.Tables.TablaVehiculos;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import utils.Global;


public class VistaMenu extends javax.swing.JFrame {
   
   private String rolUsuario;
 private PanelSubmenuUsuarioss panelSubmenuUsuarios;
 private PanelSubmenuServicios panelSubmenuServicios;

    public VistaMenu() {
         this.rolUsuario = Global.rolUsuario;
        initComponents();
        this.setLocationRelativeTo(this);
        accesosRol();

        
    }
    public VistaMenu(String cedula){
    this.rolUsuario = Global.rolUsuario;
        initComponents();
        this.setLocationRelativeTo(this);
        accesosRol();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        panelPrincipal = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        PanelMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbliconologo = new javax.swing.JLabel();
        PanelBotonesMenu = new javax.swing.JPanel();
        btnVehiculos = new javax.swing.JLabel();
        btnUsuario = new javax.swing.JLabel();
        btnciudades = new javax.swing.JLabel();
        btnServicios = new javax.swing.JLabel();
        btnFactura = new javax.swing.JLabel();
        btnCatalogo = new javax.swing.JLabel();
        btnProvedores = new javax.swing.JLabel();
        btnSalir = new javax.swing.JLabel();
        btnProductos = new javax.swing.JLabel();
        btnReportes1 = new javax.swing.JLabel();
        btnAgendarCitas1 = new javax.swing.JLabel();
        PanelHeader = new javax.swing.JPanel();
        PanelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PanelSubmenu = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);

        jDesktopPane1.setBackground(new java.awt.Color(0, 53, 79));

        panelPrincipal.setBackground(new java.awt.Color(0, 53, 79));
        panelPrincipal.setBorder(new javax.swing.border.MatteBorder(null));
        panelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        panelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 90, 810));

        PanelMenu.setBackground(new java.awt.Color(0, 53, 79));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 53, 79));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbliconologo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logote_resized.png"))); // NOI18N
        lbliconologo.setToolTipText("");
        jPanel2.add(lbliconologo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, 110));

        PanelMenu.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 180, 110));

        PanelBotonesMenu.setBackground(new java.awt.Color(0, 53, 79));
        PanelBotonesMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelBotonesMenuMouseClicked(evt);
            }
        });

        btnVehiculos.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnVehiculos.setForeground(new java.awt.Color(255, 255, 255));
        btnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/embotellamiento.png"))); // NOI18N
        btnVehiculos.setText("Vehículos");
        btnVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculosMouseClicked(evt);
            }
        });

        btnUsuario.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/agregar-usuario (1).png"))); // NOI18N
        btnUsuario.setText("Usuario");
        btnUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUsuarioMouseClicked(evt);
            }
        });

        btnciudades.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnciudades.setForeground(new java.awt.Color(255, 255, 255));
        btnciudades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/ciudad-inteligente (3).png"))); // NOI18N
        btnciudades.setText("Ciudades");
        btnciudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnciudadesMouseClicked(evt);
            }
        });

        btnServicios.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnServicios.setForeground(new java.awt.Color(255, 255, 255));
        btnServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mecanico.png"))); // NOI18N
        btnServicios.setText("Servicios");
        btnServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnServiciosMouseClicked(evt);
            }
        });

        btnFactura.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/factura (1).png"))); // NOI18N
        btnFactura.setText("Facturación");
        btnFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFacturaMouseClicked(evt);
            }
        });

        btnCatalogo.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        btnCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/servicio (1).png"))); // NOI18N
        btnCatalogo.setText("Catálogos");
        btnCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCatalogoMouseClicked(evt);
            }
        });

        btnProvedores.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnProvedores.setForeground(new java.awt.Color(255, 255, 255));
        btnProvedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/chat-web.png"))); // NOI18N
        btnProvedores.setText("Provedores");
        btnProvedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProvedoresMouseClicked(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/cerrar-sesion (2).png"))); // NOI18N
        btnSalir.setText("Logout");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        btnProductos.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/nuevo-producto (1).png"))); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProductosMouseClicked(evt);
            }
        });

        btnReportes1.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnReportes1.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/analitica.png"))); // NOI18N
        btnReportes1.setText("Reportes");
        btnReportes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReportes1MouseClicked(evt);
            }
        });

        btnAgendarCitas1.setFont(new java.awt.Font("Roboto Black", 0, 19)); // NOI18N
        btnAgendarCitas1.setForeground(new java.awt.Color(255, 255, 255));
        btnAgendarCitas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/programaCitas35.png"))); // NOI18N
        btnAgendarCitas1.setText("Agendar Citas");
        btnAgendarCitas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgendarCitas1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesMenuLayout = new javax.swing.GroupLayout(PanelBotonesMenu);
        PanelBotonesMenu.setLayout(PanelBotonesMenuLayout);
        PanelBotonesMenuLayout.setHorizontalGroup(
            PanelBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnciudades, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnVehiculos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUsuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnServicios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(PanelBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnProvedores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(PanelBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnCatalogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFactura, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addComponent(btnAgendarCitas1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        PanelBotonesMenuLayout.setVerticalGroup(
            PanelBotonesMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesMenuLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btnUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnServicios, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnProvedores, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReportes1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgendarCitas1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnciudades, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        PanelMenu.add(PanelBotonesMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 660));

        panelPrincipal.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        PanelHeader.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelHeaderLayout = new javax.swing.GroupLayout(PanelHeader);
        PanelHeader.setLayout(PanelHeaderLayout);
        PanelHeaderLayout.setHorizontalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelHeaderLayout.setVerticalGroup(
            PanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(PanelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 880, 80));

        PanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/loprincipal1.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Tu vehículo en las mejores manos, tu tiempo bien administrado");

        javax.swing.GroupLayout PanelPrincipalLayout = new javax.swing.GroupLayout(PanelPrincipal);
        PanelPrincipal.setLayout(PanelPrincipalLayout);
        PanelPrincipalLayout.setHorizontalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelPrincipalLayout.setVerticalGroup(
            PanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPrincipalLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        panelPrincipal.add(PanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 880, 620));

        PanelSubmenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelSubmenuLayout = new javax.swing.GroupLayout(PanelSubmenu);
        PanelSubmenu.setLayout(PanelSubmenuLayout);
        PanelSubmenuLayout.setHorizontalGroup(
            PanelSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        PanelSubmenuLayout.setVerticalGroup(
            PanelSubmenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        panelPrincipal.add(PanelSubmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 880, 80));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jDesktopPane1.setLayer(panelPrincipal, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(1255, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        getContentPane().add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1366, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


//CrudPanelCliente crudCli = new CrudPanelCliente();
    private void btnUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUsuarioMouseClicked
        PanelTituloUsuario titUsu = new PanelTituloUsuario();
        PanelSubmenuUsuarioss SubmenuUsu = new PanelSubmenuUsuarioss();
//        TablaUsuarios tablaUsu = new TablaUsuarios();
        MostrarpanelTitulo(titUsu);
        MostrarpanelSubmenu(SubmenuUsu);
//        MostarpanelCruds(tablaUsu);
    }//GEN-LAST:event_btnUsuarioMouseClicked

    private void btnServiciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnServiciosMouseClicked
        TablaServicios tablaPro = new TablaServicios();
        PanelTituloServicios titSer = new PanelTituloServicios(); 
        PanelSubmenuServicios Submenuserv = new PanelSubmenuServicios();         
        MostrarpanelTitulo(titSer);
        MostrarpanelSubmenu(Submenuserv);
        MostarpanelCruds(tablaPro);
    }//GEN-LAST:event_btnServiciosMouseClicked

    private void btnFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFacturaMouseClicked
       
        PanelTituloFacturacion titufac = new PanelTituloFacturacion();
        PanelSubmenuFacturacion SubmenuFac = new PanelSubmenuFacturacion();
        Factura fac =new Factura();
        MostrarpanelTitulo(titufac);
        MostrarpanelSubmenu(SubmenuFac);
        MostarpanelCruds(fac);
    }//GEN-LAST:event_btnFacturaMouseClicked

    private void btnCatalogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCatalogoMouseClicked
      PanelTituloCatalogo tituCat = new PanelTituloCatalogo();
        PanelSubmenuCatalogo SubmenuCat = new PanelSubmenuCatalogo(); 
        CatalogoProductos catpro =new CatalogoProductos();
        MostrarpanelTitulo(tituCat);
        MostrarpanelSubmenu(SubmenuCat);
        MostarpanelCruds(catpro);
        
        
    }//GEN-LAST:event_btnCatalogoMouseClicked
    
    
    private void PanelBotonesMenuMouseClicked(java.awt.event.MouseEvent evt) {                                        
        System.out.println("nada");
        
    }
    
    
    
    private void btnProvedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProvedoresMouseClicked
        TablaProveedor prov = new TablaProveedor();
        PanelTituloProvedores titPro = new PanelTituloProvedores();
        PanelSubmenuProveedores submenProv = new PanelSubmenuProveedores();
        MostrarpanelSubmenu(submenProv);
        MostrarpanelTitulo(titPro);
        MostarpanelCruds(prov);
    }//GEN-LAST:event_btnProvedoresMouseClicked

    private void btnciudadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnciudadesMouseClicked
       PanelTituloCiudades titciu = new PanelTituloCiudades();
        PanelSUbmenuCiudades submeciu = new PanelSUbmenuCiudades();
        MostrarpanelSubmenu(submeciu);
        MostrarpanelTitulo(titciu);  
    }//GEN-LAST:event_btnciudadesMouseClicked

    private void btnProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProductosMouseClicked
         TablaProductos prod = new TablaProductos();
        PanelTituloProducto titProd = new PanelTituloProducto();
        PanelSubmenuProductos submenProd = new PanelSubmenuProductos();
        MostrarpanelSubmenu(submenProd);
        MostrarpanelTitulo(titProd);
        MostarpanelCruds(prod);
    }//GEN-LAST:event_btnProductosMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
       Home homesito=new Home();
     homesito.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnReportes1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReportes1MouseClicked
        PanelTituloReporte titreo = new PanelTituloReporte();
        PanelSubmenuReportes submenrep = new PanelSubmenuReportes();
        MostrarpanelSubmenu(submenrep);
        MostrarpanelTitulo(titreo);
    }//GEN-LAST:event_btnReportes1MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel4MouseClicked

    private void btnAgendarCitas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgendarCitas1MouseClicked
       PanelTituloCitas titcit = new PanelTituloCitas();
        PanelSUbmenuCitas submecitas = new PanelSUbmenuCitas();
        Citas cit = new Citas();
        MostrarpanelSubmenu(submecitas);
        MostrarpanelTitulo(titcit);
        MostarpanelCruds(cit);
    }//GEN-LAST:event_btnAgendarCitas1MouseClicked

    private void btnVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculosMouseClicked
        TablaVehiculos miVehi = new TablaVehiculos();
        PanelTituloVehiculo titcit = new PanelTituloVehiculo();
        PanelSubmenuAuto submecitas = new PanelSubmenuAuto();
        MostrarpanelSubmenu(submecitas);
        MostrarpanelTitulo(titcit);
        MostarpanelCruds(miVehi);
    }//GEN-LAST:event_btnVehiculosMouseClicked
     private void accesosRol() {
        System.out.println("Rol del usuario: " + rolUsuario);

        switch (rolUsuario) {
            case "CLIENTE":
                deshabilitarComponentesCliente();
                break;
            case "ADMINISTRADOR":
                deshabilitarComponentesAdministrador();
                break;
            case "VENDEDOR":
                deshabilitarComponentesVendedor();
                break;
            case "MECANICO":
                deshabilitarComponentesMecanico();
                break;
            default:
                JOptionPane.showMessageDialog(null, "Rol no reconocido");
                break;
        }
    }
 private void deshabilitarComponentesAdministrador() {
        // Administrador tiene acceso a todo
    }
 private void deshabilitarComponentesCliente() {
        btnFactura.setVisible(false);
        btnServicios.setVisible(false);
        btnProductos.setVisible(false);
        btnProvedores.setVisible(false);
        btnciudades.setVisible(false);
        btnReportes1.setVisible(false);
    }
 private void deshabilitarComponentesVendedor() {
        btnReportes1.setVisible(false);
        btnVehiculos.setVisible(false);
       
    }

      private void deshabilitarComponentesMecanico() {
        btnUsuario.setVisible(false);
        btnProductos.setVisible(false);
        btnProvedores.setVisible(false);
        btnciudades.setVisible(false);
        btnReportes1.setVisible(false);
        btnAgendarCitas1.setVisible(false);
        btnCatalogo.setVisible(false);
        btnFactura.setVisible(false);
       
    }
    private void actualizarVisibilidadSubmenuUsuarios() {
        if (panelSubmenuUsuarios != null) {

            switch (rolUsuario) {
                case "VENDEDOR":
                    panelSubmenuUsuarios.getBtnAdministrador().setVisible(false);
                    panelSubmenuUsuarios.getBtnMecanico().setVisible(false);
                    panelSubmenuUsuarios.getBtnVendedor().setVisible(false);
                    System.out.println("Botones del submenu de usuarios deshabilitados para el rol VENDEDOR");
                    break;
                case "CLIENTE":
                    panelSubmenuUsuarios.getBtnAdministrador().setVisible(false);
                    panelSubmenuUsuarios.getBtnMecanico().setVisible(false);
                    panelSubmenuUsuarios.getBtnVendedor().setVisible(false);
                    System.out.println("Botones del submenu de usuarios deshabilitados para el rol Cliente");
                    break;  
            }
        }
    }
 private void actualizarVisibilidadSubmenuServicios() {
        if (panelSubmenuServicios != null) {
           
            switch (rolUsuario) {
               
                case "MECANICO":
                    panelSubmenuServicios.getBtnCategoria1().setVisible(false);
                    panelSubmenuServicios.getBtngestionser1().setVisible(false);
                    
                    break;
                
            }
        } 
    }

    private void MostrarpanelSubmenu(JPanel p) {
        p.setSize(870, 80);
        p.setLocation(0, 0);
        PanelSubmenu.removeAll();
        PanelSubmenu.add(p, BorderLayout.CENTER);
        PanelSubmenu.revalidate();
        PanelSubmenu.repaint();

    }

    private void MostrarpanelTitulo(JPanel p) {
        p.setSize(870, 80);
        p.setLocation(0, 0);
        PanelHeader.removeAll();
        PanelHeader.add(p, BorderLayout.CENTER);
        PanelHeader.revalidate();
        PanelHeader.repaint();
    }

    private void MostarpanelCruds(JPanel p) {
        p.setSize(900, 660);
        p.setLocation(0, 0);
        PanelPrincipal.removeAll();
        PanelPrincipal.add(p, BorderLayout.CENTER);
        PanelPrincipal.revalidate();
        PanelPrincipal.repaint();
    }

    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBotonesMenu;
    public static javax.swing.JPanel PanelHeader;
    private javax.swing.JPanel PanelMenu;
    public static javax.swing.JPanel PanelPrincipal;
    public static javax.swing.JPanel PanelSubmenu;
    private javax.swing.JLabel btnAgendarCitas1;
    private javax.swing.JLabel btnCatalogo;
    private javax.swing.JLabel btnFactura;
    private javax.swing.JLabel btnProductos;
    private javax.swing.JLabel btnProvedores;
    private javax.swing.JLabel btnReportes1;
    private javax.swing.JLabel btnSalir;
    private javax.swing.JLabel btnServicios;
    private javax.swing.JLabel btnUsuario;
    private javax.swing.JLabel btnVehiculos;
    private javax.swing.JLabel btnciudades;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbliconologo;
    public javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
